name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy to EC2 on main branch push or PR
    runs-on: ubuntu-latest

    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo -u shiny bash
            cd /srv/shiny-server/test-shiny-server
            git pull